package com.oj.domain;
// Generated 11 Mar, 2018 2:08:06 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name="Admin"
    ,catalog="OnlineJudge"
)
public class Admin  implements java.io.Serializable {


     private String username;
     private String email;
     private String password;
     private Set<Problems> problemses = new HashSet<Problems>(0);
     private Set<Contests> contestses = new HashSet<Contests>(0);

    public Admin() {
    }

	
    public Admin(String username, String email, String password) {
        this.username = username;
        this.email = email;
        this.password = password;
    }
    public Admin(String username, String email, String password, Set<Problems> problemses, Set<Contests> contestses) {
       this.username = username;
       this.email = email;
       this.password = password;
       this.problemses = problemses;
       this.contestses = contestses;
    }
   
     @Id 

    
    @Column(name="username", unique=true, nullable=false, length=15)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="email", nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password", nullable=false, length=15)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="admin")
    public Set<Problems> getProblemses() {
        return this.problemses;
    }
    
    public void setProblemses(Set<Problems> problemses) {
        this.problemses = problemses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="admin")
    public Set<Contests> getContestses() {
        return this.contestses;
    }
    
    public void setContestses(Set<Contests> contestses) {
        this.contestses = contestses;
    }




}


