package com.oj.domain;
// Generated 11 Mar, 2018 2:08:06 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Assignments generated by hbm2java
 */
@Entity
@Table(name="Assignments"
    ,catalog="OnlineJudge"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class Assignments  implements java.io.Serializable {


     private String assignmentid;
     private CampusChapter campusChapter;
     private String name;
     private Date starttime;
     private Date endtime;

    public Assignments() {
    }

    public Assignments(String assignmentid, CampusChapter campusChapter, String name, Date starttime, Date endtime) {
       this.assignmentid = assignmentid;
       this.campusChapter = campusChapter;
       this.name = name;
       this.starttime = starttime;
       this.endtime = endtime;
    }
   
     @Id 

    
    @Column(name="assignmentid", unique=true, nullable=false, length=15)
    public String getAssignmentid() {
        return this.assignmentid;
    }
    
    public void setAssignmentid(String assignmentid) {
        this.assignmentid = assignmentid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="collegeid", nullable=false)
    public CampusChapter getCampusChapter() {
        return this.campusChapter;
    }
    
    public void setCampusChapter(CampusChapter campusChapter) {
        this.campusChapter = campusChapter;
    }

    
    @Column(name="name", unique=true, nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="starttime", nullable=false, length=19)
    public Date getStarttime() {
        return this.starttime;
    }
    
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="endtime", nullable=false, length=19)
    public Date getEndtime() {
        return this.endtime;
    }
    
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }




}


