package com.oj.domain;
// Generated 11 Mar, 2018 2:08:06 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CampusChapter generated by hbm2java
 */
@Entity
@Table(name="CampusChapter"
    ,catalog="OnlineJudge"
    , uniqueConstraints = {@UniqueConstraint(columnNames="faculty_rep"), @UniqueConstraint(columnNames="fullname"), @UniqueConstraint(columnNames="student_rep1"), @UniqueConstraint(columnNames="student_rep2")} 
)
public class CampusChapter  implements java.io.Serializable {


     private String collegeid;
     private User userByStudentRep2;
     private User userByStudentRep1;
     private User userByFacultyRep;
     private String fullname;
     private String address;
     private String country;
     private String state;
     private String city;
     private Set<Assignments> assignmentses = new HashSet<Assignments>(0);

    public CampusChapter() {
    }

	
    public CampusChapter(String collegeid, User userByStudentRep2, User userByStudentRep1, User userByFacultyRep, String fullname, String address, String country, String state, String city) {
        this.collegeid = collegeid;
        this.userByStudentRep2 = userByStudentRep2;
        this.userByStudentRep1 = userByStudentRep1;
        this.userByFacultyRep = userByFacultyRep;
        this.fullname = fullname;
        this.address = address;
        this.country = country;
        this.state = state;
        this.city = city;
    }
    public CampusChapter(String collegeid, User userByStudentRep2, User userByStudentRep1, User userByFacultyRep, String fullname, String address, String country, String state, String city, Set<Assignments> assignmentses) {
       this.collegeid = collegeid;
       this.userByStudentRep2 = userByStudentRep2;
       this.userByStudentRep1 = userByStudentRep1;
       this.userByFacultyRep = userByFacultyRep;
       this.fullname = fullname;
       this.address = address;
       this.country = country;
       this.state = state;
       this.city = city;
       this.assignmentses = assignmentses;
    }
   
     @Id 

    
    @Column(name="collegeid", unique=true, nullable=false, length=10)
    public String getCollegeid() {
        return this.collegeid;
    }
    
    public void setCollegeid(String collegeid) {
        this.collegeid = collegeid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="student_rep2", unique=true, nullable=false)
    public User getUserByStudentRep2() {
        return this.userByStudentRep2;
    }
    
    public void setUserByStudentRep2(User userByStudentRep2) {
        this.userByStudentRep2 = userByStudentRep2;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="student_rep1", unique=true, nullable=false)
    public User getUserByStudentRep1() {
        return this.userByStudentRep1;
    }
    
    public void setUserByStudentRep1(User userByStudentRep1) {
        this.userByStudentRep1 = userByStudentRep1;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="faculty_rep", unique=true, nullable=false)
    public User getUserByFacultyRep() {
        return this.userByFacultyRep;
    }
    
    public void setUserByFacultyRep(User userByFacultyRep) {
        this.userByFacultyRep = userByFacultyRep;
    }

    
    @Column(name="fullname", unique=true, nullable=false, length=100)
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    
    @Column(name="address", nullable=false, length=150)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="country", nullable=false, length=15)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    
    @Column(name="state", nullable=false, length=15)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="city", nullable=false, length=15)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="campusChapter")
    public Set<Assignments> getAssignmentses() {
        return this.assignmentses;
    }
    
    public void setAssignmentses(Set<Assignments> assignmentses) {
        this.assignmentses = assignmentses;
    }




}


