package com.oj.domain;
// Generated 11 Mar, 2018 2:08:06 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comments generated by hbm2java
 */
@Entity
@Table(name="Comments"
    ,catalog="OnlineJudge"
)
public class Comments  implements java.io.Serializable {


     private Long id;
     private Discuss discuss;
     private User user;
     private String body;
     private Date datetime;
     private boolean approved;
     private Set<Reply> replies = new HashSet<Reply>(0);
     private Set<UserLikesComments> userLikesCommentses = new HashSet<UserLikesComments>(0);

    public Comments() {
    }

	
    public Comments(Discuss discuss, User user, String body, Date datetime) {
        this.discuss = discuss;
        this.user = user;
        this.body = body;
        this.datetime = datetime;
    }
    public Comments(Discuss discuss, User user, String body, Date datetime, Set<Reply> replies, Set<UserLikesComments> userLikesCommentses) {
       this.discuss = discuss;
       this.user = user;
       this.body = body;
       this.datetime = datetime;
       this.replies = replies;
       this.userLikesCommentses = userLikesCommentses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="questionid", nullable=false)
    public Discuss getDiscuss() {
        return this.discuss;
    }
    
    public void setDiscuss(Discuss discuss) {
        this.discuss = discuss;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="username", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="body", nullable=false, length=4096)
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datetime", nullable=false, length=19)
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
    
    @Column(name="approved")
    public boolean isApproved() {
        return this.approved;
    }
    
    public void setApproved(boolean approved) {
        this.approved = approved;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comments")
    public Set<Reply> getReplies() {
        return this.replies;
    }
    
    public void setReplies(Set<Reply> replies) {
        this.replies = replies;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comments")
    public Set<UserLikesComments> getUserLikesCommentses() {
        return this.userLikesCommentses;
    }
    
    public void setUserLikesCommentses(Set<UserLikesComments> userLikesCommentses) {
        this.userLikesCommentses = userLikesCommentses;
    }




}


