package com.oj.domain;
// Generated 11 Mar, 2018 2:08:06 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Contests generated by hbm2java
 */
@Entity
@Table(name="Contests"
    ,catalog="OnlineJudge"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class Contests  implements java.io.Serializable {


     private String contestcode;
     private Admin admin;
     private String name;
     private Date starttime;
     private Date endtime;
     private boolean israted;

    public Contests() {
    }

    public Contests(String contestcode, Admin admin, String name, Date starttime, Date endtime, boolean israted) {
       this.contestcode = contestcode;
       this.admin = admin;
       this.name = name;
       this.starttime = starttime;
       this.endtime = endtime;
       this.israted = israted;
    }
   
     @Id 

    
    @Column(name="contestcode", unique=true, nullable=false, length=15)
    public String getContestcode() {
        return this.contestcode;
    }
    
    public void setContestcode(String contestcode) {
        this.contestcode = contestcode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="hostedby", nullable=false)
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }

    
    @Column(name="name", unique=true, nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="starttime", nullable=false, length=19)
    public Date getStarttime() {
        return this.starttime;
    }
    
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="endtime", nullable=false, length=19)
    public Date getEndtime() {
        return this.endtime;
    }
    
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    
    @Column(name="israted", nullable=false)
    public boolean isIsrated() {
        return this.israted;
    }
    
    public void setIsrated(boolean israted) {
        this.israted = israted;
    }




}


