package com.oj.domain;
// Generated 11 Mar, 2018 2:08:06 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Discuss generated by hbm2java
 */
@Entity
@Table(name="Discuss"
    ,catalog="OnlineJudge"
)
public class Discuss  implements java.io.Serializable {


     private Long questionid;
     private User user;
     private String title;
     private String body;
     private String datetime;
     private String visibleto;
     private Set<Comments> commentses = new HashSet<Comments>(0);

    public Discuss() {
    }

	
    public Discuss(User user, String title, String body, String datetime) {
        this.user = user;
        this.title = title;
        this.body = body;
        this.datetime = datetime;
    }
    public Discuss(User user, String title, String body, String datetime, String visibleto, Set<Comments> commentses) {
       this.user = user;
       this.title = title;
       this.body = body;
       this.datetime = datetime;
       this.visibleto = visibleto;
       this.commentses = commentses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="questionid", unique=true, nullable=false)
    public Long getQuestionid() {
        return this.questionid;
    }
    
    public void setQuestionid(Long questionid) {
        this.questionid = questionid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="username")
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="title", nullable=false, length=100)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="body", nullable=false, length=4096)
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }

    
    @Column(name="datetime", nullable=false, length=45)
    public String getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(String datetime) {
        this.datetime = datetime;
    }

    
    @Column(name="visibleto", length=15)
    public String getVisibleto() {
        return this.visibleto;
    }
    
    public void setVisibleto(String visibleto) {
        this.visibleto = visibleto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="discuss")
    public Set<Comments> getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set<Comments> commentses) {
        this.commentses = commentses;
    }




}


