package com.oj.domain;
// Generated 11 Mar, 2018 2:08:06 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Problems generated by hbm2java
 */
@Entity
@Table(name="Problems"
    ,catalog="OnlineJudge"
)
public class Problems  implements java.io.Serializable {


     private String problemcode;
     private Admin admin;
     private User user;
     private String problempath;
     private String difficulty;
     private boolean visibletoall;
     private float timelimit;
     private float memorylimit;
     private String belongsto;
     private Set<Submissions> submissionses = new HashSet<Submissions>(0);

    public Problems() {
    }

	
    public Problems(String problemcode, User user, String problempath, String difficulty, boolean visibletoall, float timelimit, float memorylimit, String belongsto) {
        this.problemcode = problemcode;
        this.user = user;
        this.problempath = problempath;
        this.difficulty = difficulty;
        this.visibletoall = visibletoall;
        this.timelimit = timelimit;
        this.memorylimit = memorylimit;
        this.belongsto = belongsto;
    }
    public Problems(String problemcode, Admin admin, User user, String problempath, String difficulty, boolean visibletoall, float timelimit, float memorylimit, String belongsto, Set<Submissions> submissionses) {
       this.problemcode = problemcode;
       this.admin = admin;
       this.user = user;
       this.problempath = problempath;
       this.difficulty = difficulty;
       this.visibletoall = visibletoall;
       this.timelimit = timelimit;
       this.memorylimit = memorylimit;
       this.belongsto = belongsto;
       this.submissionses = submissionses;
    }
   
     @Id 

    
    @Column(name="problemcode", unique=true, nullable=false, length=15)
    public String getProblemcode() {
        return this.problemcode;
    }
    
    public void setProblemcode(String problemcode) {
        this.problemcode = problemcode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="approvedby")
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="setter", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="problempath", nullable=false, length=100)
    public String getProblempath() {
        return this.problempath;
    }
    
    public void setProblempath(String problempath) {
        this.problempath = problempath;
    }

    
    @Column(name="difficulty", nullable=false, length=10)
    public String getDifficulty() {
        return this.difficulty;
    }
    
    public void setDifficulty(String difficulty) {
        this.difficulty = difficulty;
    }

    
    @Column(name="visibletoall", nullable=false)
    public boolean isVisibletoall() {
        return this.visibletoall;
    }
    
    public void setVisibletoall(boolean visibletoall) {
        this.visibletoall = visibletoall;
    }

    
    @Column(name="timelimit", nullable=false, precision=12, scale=0)
    public float getTimelimit() {
        return this.timelimit;
    }
    
    public void setTimelimit(float timelimit) {
        this.timelimit = timelimit;
    }

    
    @Column(name="memorylimit", nullable=false, precision=12, scale=0)
    public float getMemorylimit() {
        return this.memorylimit;
    }
    
    public void setMemorylimit(float memorylimit) {
        this.memorylimit = memorylimit;
    }

    
    @Column(name="belongsto", nullable=false, length=15)
    public String getBelongsto() {
        return this.belongsto;
    }
    
    public void setBelongsto(String belongsto) {
        this.belongsto = belongsto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="problems")
    public Set<Submissions> getSubmissionses() {
        return this.submissionses;
    }
    
    public void setSubmissionses(Set<Submissions> submissionses) {
        this.submissionses = submissionses;
    }




}


