package com.oj.domain;
// Generated 11 Mar, 2018 2:08:06 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Submissions generated by hbm2java
 */
@Entity
@Table(name="Submissions"
    ,catalog="OnlineJudge"
)
public class Submissions  implements java.io.Serializable {


     private Long submissionid;
     private Problems problems;
     private User user;
     private String codepath;
     private String verdict;
     private float timetaken;
     private float memoryused;
     private String lan;
    public Submissions() {
    }

    public Submissions(Problems problems, User user, String codepath, String verdict, float timetaken, float memoryused, String lan) {
       this.problems = problems;
       this.user = user;
       this.codepath = codepath;
       this.verdict = verdict;
       this.timetaken = timetaken;
       this.memoryused = memoryused;
       this.lan=lan;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="submissionid", unique=true, nullable=false)
    public Long getSubmissionid() {
        return this.submissionid;
    }
    
    public void setSubmissionid(Long submissionid) {
        this.submissionid = submissionid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="problem")
    public Problems getProblems() {
        return this.problems;
    }
    
    public void setProblems(Problems problems) {
        this.problems = problems;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="username")
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="codepath", length=100)
    public String getCodepath() {
        return this.codepath;
    }
    
    public void setCodepath(String codepath) {
        this.codepath = codepath;
    }

    
    @Column(name="verdict", length=15)
    public String getVerdict() {
        return this.verdict;
    }
    
    public void setVerdict(String verdict) {
        this.verdict = verdict;
    }

    
    @Column(name="timetaken", precision=12, scale=0)
    public float getTimetaken() {
        return this.timetaken;
    }
    
    public void setTimetaken(float timetaken) {
        this.timetaken = timetaken;
    }

    
    @Column(name="memoryused", precision=12, scale=0)
    public float getMemoryused() {
        return this.memoryused;
    }
    
    public void setMemoryused(float memoryused) {
        this.memoryused = memoryused;
    }
    @Column(name="lan", length=45)
    public String getLan() {
        return lan;
    }

    public void setLan(String lan) {
        this.lan = lan;
    }




}


