package com.oj.domain;
// Generated 11 Mar, 2018 2:08:06 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="User"
    ,catalog="OnlineJudge"
)
public class User  implements java.io.Serializable {


     private String username;
     private String fullname;
     private String email;
     private String mobile;
     private String password;
     private String institution;
     private String country;
     private String state;
     private String city;
     private String aboutme;
     private String motto;
     private String position;
     private String link;
     private Integer ratings;
     private Integer globelRank;
     private Integer countryRank;
     private Set<Discuss> discusses = new HashSet<Discuss>(0);
     private Set<Reply> replies = new HashSet<Reply>(0);
     private Set<CampusChapter> campusChaptersForStudentRep2 = new HashSet<CampusChapter>(0);
     private Set<CampusChapter> campusChaptersForStudentRep1 = new HashSet<CampusChapter>(0);
     private Set<CampusChapter> campusChaptersForFacultyRep = new HashSet<CampusChapter>(0);
     private Set<Comments> commentses = new HashSet<Comments>(0);
     private Set<Problems> problemses = new HashSet<Problems>(0);
     private Set<Submissions> submissionses = new HashSet<Submissions>(0);
     private Set<UserLikesComments> userLikesCommentses = new HashSet<UserLikesComments>(0);

    public User() {
    }

	
    public User(String username, String fullname, String email, String password, String institution, String country, String state, String city, String position) {
        this.username = username;
        this.fullname = fullname;
        this.email = email;
        this.password = password;
        this.institution = institution;
        this.country = country;
        this.state = state;
        this.city = city;
        this.position = position;
    }
    public User(String username, String fullname, String email, String mobile, String password, String institution, String country, String state, String city, String aboutme, String motto, String position, String link, Integer ratings, Integer globelRank, Integer countryRank, Set<Discuss> discusses, Set<Reply> replies, Set<CampusChapter> campusChaptersForStudentRep2, Set<CampusChapter> campusChaptersForStudentRep1, Set<CampusChapter> campusChaptersForFacultyRep, Set<Comments> commentses, Set<Problems> problemses, Set<Submissions> submissionses, Set<UserLikesComments> userLikesCommentses) {
       this.username = username;
       this.fullname = fullname;
       this.email = email;
       this.mobile = mobile;
       this.password = password;
       this.institution = institution;
       this.country = country;
       this.state = state;
       this.city = city;
       this.aboutme = aboutme;
       this.motto = motto;
       this.position = position;
       this.link = link;
       this.ratings = ratings;
       this.globelRank = globelRank;
       this.countryRank = countryRank;
       this.discusses = discusses;
       this.replies = replies;
       this.campusChaptersForStudentRep2 = campusChaptersForStudentRep2;
       this.campusChaptersForStudentRep1 = campusChaptersForStudentRep1;
       this.campusChaptersForFacultyRep = campusChaptersForFacultyRep;
       this.commentses = commentses;
       this.problemses = problemses;
       this.submissionses = submissionses;
       this.userLikesCommentses = userLikesCommentses;
    }
   
     @Id 

    
    @Column(name="username", unique=true, nullable=false, length=10)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="fullname", nullable=false, length=30)
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    
    @Column(name="email", nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="mobile", length=20)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    
    @Column(name="password", nullable=false, length=15)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="institution", nullable=false, length=50)
    public String getInstitution() {
        return this.institution;
    }
    
    public void setInstitution(String institution) {
        this.institution = institution;
    }

    
    @Column(name="country", nullable=false, length=15)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    
    @Column(name="state", nullable=false, length=15)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="city", nullable=false, length=15)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="aboutme", length=150)
    public String getAboutme() {
        return this.aboutme;
    }
    
    public void setAboutme(String aboutme) {
        this.aboutme = aboutme;
    }

    
    @Column(name="motto", length=150)
    public String getMotto() {
        return this.motto;
    }
    
    public void setMotto(String motto) {
        this.motto = motto;
    }

    
    @Column(name="position", nullable=false, length=15)
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }

    
    @Column(name="link", length=100)
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }

    
    @Column(name="ratings")
    public Integer getRatings() {
        return this.ratings;
    }
    
    public void setRatings(Integer ratings) {
        this.ratings = ratings;
    }

    
    @Column(name="globel_rank")
    public Integer getGlobelRank() {
        return this.globelRank;
    }
    
    public void setGlobelRank(Integer globelRank) {
        this.globelRank = globelRank;
    }

    
    @Column(name="country_rank")
    public Integer getCountryRank() {
        return this.countryRank;
    }
    
    public void setCountryRank(Integer countryRank) {
        this.countryRank = countryRank;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Discuss> getDiscusses() {
        return this.discusses;
    }
    
    public void setDiscusses(Set<Discuss> discusses) {
        this.discusses = discusses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Reply> getReplies() {
        return this.replies;
    }
    
    public void setReplies(Set<Reply> replies) {
        this.replies = replies;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userByStudentRep2")
    public Set<CampusChapter> getCampusChaptersForStudentRep2() {
        return this.campusChaptersForStudentRep2;
    }
    
    public void setCampusChaptersForStudentRep2(Set<CampusChapter> campusChaptersForStudentRep2) {
        this.campusChaptersForStudentRep2 = campusChaptersForStudentRep2;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userByStudentRep1")
    public Set<CampusChapter> getCampusChaptersForStudentRep1() {
        return this.campusChaptersForStudentRep1;
    }
    
    public void setCampusChaptersForStudentRep1(Set<CampusChapter> campusChaptersForStudentRep1) {
        this.campusChaptersForStudentRep1 = campusChaptersForStudentRep1;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userByFacultyRep")
    public Set<CampusChapter> getCampusChaptersForFacultyRep() {
        return this.campusChaptersForFacultyRep;
    }
    
    public void setCampusChaptersForFacultyRep(Set<CampusChapter> campusChaptersForFacultyRep) {
        this.campusChaptersForFacultyRep = campusChaptersForFacultyRep;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Comments> getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set<Comments> commentses) {
        this.commentses = commentses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Problems> getProblemses() {
        return this.problemses;
    }
    
    public void setProblemses(Set<Problems> problemses) {
        this.problemses = problemses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Submissions> getSubmissionses() {
        return this.submissionses;
    }
    
    public void setSubmissionses(Set<Submissions> submissionses) {
        this.submissionses = submissionses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<UserLikesComments> getUserLikesCommentses() {
        return this.userLikesCommentses;
    }
    
    public void setUserLikesCommentses(Set<UserLikesComments> userLikesCommentses) {
        this.userLikesCommentses = userLikesCommentses;
    }




}


