package com.oj.domain;
// Generated 11 Mar, 2018 2:08:06 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserLikesCommentsId generated by hbm2java
 */
@Embeddable
public class UserLikesCommentsId  implements java.io.Serializable {


     private String username;
     private long commentsId;

    public UserLikesCommentsId() {
    }

    public UserLikesCommentsId(String username, long commentsId) {
       this.username = username;
       this.commentsId = commentsId;
    }
   


    @Column(name="username", nullable=false, length=10)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }


    @Column(name="Comments_id", nullable=false)
    public long getCommentsId() {
        return this.commentsId;
    }
    
    public void setCommentsId(long commentsId) {
        this.commentsId = commentsId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserLikesCommentsId) ) return false;
		 UserLikesCommentsId castOther = ( UserLikesCommentsId ) other; 
         
		 return ( (this.getUsername()==castOther.getUsername()) || ( this.getUsername()!=null && castOther.getUsername()!=null && this.getUsername().equals(castOther.getUsername()) ) )
 && (this.getCommentsId()==castOther.getCommentsId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUsername() == null ? 0 : this.getUsername().hashCode() );
         result = 37 * result + (int) this.getCommentsId();
         return result;
   }   


}


